apiVersion: hrivnak.org/v1alpha1
kind: Watch
metadata:
  name: example
spec:
  serviceName: memweb-reconciler
  group: cache.example.com
  version: v1alpha1
  kind: Memcached
  ownedWatches:
    - Group: apps
      Version: v1
      Kind: Deployment
