apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: central-operator
  template:
    metadata:
      labels:
        name: central-operator
    spec:
      serviceAccountName: central-operator
      containers:
        - name: central-operator
          # Replace this with the built image name
          image: docker.io/mhrivnak/central-operator
          command:
          - central-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "central-operator"
