// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/mhrivnak/central-operator/pkg/apis/hrivnak/v1alpha1.Watch":       schema_pkg_apis_hrivnak_v1alpha1_Watch(ref),
		"github.com/mhrivnak/central-operator/pkg/apis/hrivnak/v1alpha1.WatchSpec":   schema_pkg_apis_hrivnak_v1alpha1_WatchSpec(ref),
		"github.com/mhrivnak/central-operator/pkg/apis/hrivnak/v1alpha1.WatchStatus": schema_pkg_apis_hrivnak_v1alpha1_WatchStatus(ref),
	}
}

func schema_pkg_apis_hrivnak_v1alpha1_Watch(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Watch is the Schema for the watches API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/mhrivnak/central-operator/pkg/apis/hrivnak/v1alpha1.WatchSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/mhrivnak/central-operator/pkg/apis/hrivnak/v1alpha1.WatchStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/mhrivnak/central-operator/pkg/apis/hrivnak/v1alpha1.WatchSpec", "github.com/mhrivnak/central-operator/pkg/apis/hrivnak/v1alpha1.WatchStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_hrivnak_v1alpha1_WatchSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "WatchSpec defines the desired state of Watch",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"ServiceName": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL SPEC FIELDS - desired state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"Group": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"Version": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"Kind": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
				Required: []string{"ServiceName", "Group", "Version", "Kind"},
			},
		},
	}
}

func schema_pkg_apis_hrivnak_v1alpha1_WatchStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "WatchStatus defines the observed state of Watch",
				Type:        []string{"object"},
			},
		},
	}
}
